# Configuration for https://www.patternsoflife.nl/
title: Patterns of Life
baseurl: "/"
url: "https://www.patternsoflife.nl"
lang: nl

# Build settings
markdown: kramdown
remote_theme: patternsoflife/pages-theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Whether to show excerpts on the homepage
show_excerpts: false

# Minima theme settings
minima:

  # See https://shopify.github.io/liquid/filters/date/
  date_format: "%d %B %Y"

# Pages to show in header
header_pages:
 - over.md
 - nieuws.md
 - team.md
 - publicaties.md

# Paths to exclude from processing
exclude:
  - README.md

# See https://jekyllrb.com/docs/collections/
collections:
  team:
    output: true
    permalink: /team/:name
